version: 1
accounts:
- name: alice
  coins:
  - 20000rupx
  - 200000000stake
- name: bob
  coins:
  - 10000rupx
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5rupx
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
